/**
 * Serialize/deserialize a GameState to a portable save file.
 *
 * Only the geometric layer (vertices, edges) and ID counters are saved.
 * regions/subpositions, vertex degree/type/visual, isPseudo vertices, and
 * edge leftRegion/rightRegion are all rebuilt by recomputeRegions() from
 * vertices+edges alone (see model/moves.ts), so none of that is stored here.
 * Voronoi-cell data is likewise never saved — it's cheap to recompute on
 * demand from the saved board via buildSubregionHighlight/buildVoronoiGraph.
 */

import type { GameState, VertexId, EdgeId } from './types';
import { VertexType, VertexVisualState } from './types';
import type { SpherePoint, RotationMatrix } from '../math/sphere';
import type { ParsedMove } from './moveCodeParse';
import { parseToken } from './moveCodeParse';

const SCHEMA_VERSION = 1;

interface SavedVertex {
  id: VertexId;
  pos: SpherePoint;
  isMidpoint?: boolean;
}

interface SavedEdge {
  id: EdgeId;
  v1: VertexId;
  v2: VertexId;
  points: SpherePoint[];
}

export interface SaveFileV1 {
  schemaVersion: 1;
  currentSpotCount: number;
  moveCount: number;
  nextVertexId: VertexId;
  nextEdgeId: EdgeId;
  vertices: SavedVertex[];
  edges: SavedEdge[];
  camera: RotationMatrix;
  moveSequence: string[];
  pendingMove: { token: string } | null;
}

export function serializeGameState(
  state: GameState,
  camera: RotationMatrix,
  currentSpotCount: number,
  moveSequence: readonly string[],
  pendingMoveToken: string | null,
): SaveFileV1 {
  const vertices: SavedVertex[] = [];
  for (const v of state.vertices.values()) {
    if (v.isPseudo) continue; // regenerated by recomputeRegions; not real board state
    vertices.push({ id: v.id, pos: { ...v.pos }, isMidpoint: v.isMidpoint });
  }
  const edges: SavedEdge[] = [];
  for (const e of state.edges.values()) {
    edges.push({ id: e.id, v1: e.v1, v2: e.v2, points: e.points.map(p => ({ ...p })) });
  }
  return {
    schemaVersion: SCHEMA_VERSION,
    currentSpotCount,
    moveCount: state.moveCount,
    nextVertexId: state.nextVertexId,
    nextEdgeId: state.nextEdgeId,
    vertices,
    edges,
    camera: [...camera] as RotationMatrix,
    moveSequence: [...moveSequence],
    pendingMove: pendingMoveToken !== null ? { token: pendingMoveToken } : null,
  };
}

export interface DeserializedSave {
  state: GameState;
  camera: RotationMatrix;
  currentSpotCount: number;
  moveSequence: string[];
  pendingMove: ParsedMove | null;
}

export function deserializeGameState(save: SaveFileV1): DeserializedSave {
  if (save.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`Unsupported save schemaVersion ${String(save.schemaVersion)} (expected ${SCHEMA_VERSION}).`);
  }

  const vertices: GameState['vertices'] = new Map();
  for (const v of save.vertices) {
    vertices.set(v.id, {
      id: v.id,
      pos: { ...v.pos },
      // Placeholders — overwritten by recomputeRegions()'s degree/classification pass.
      type: VertexType.Spot,
      degree: 0,
      visual: VertexVisualState.Active,
      isMidpoint: v.isMidpoint,
    });
  }

  const edges: GameState['edges'] = new Map();
  for (const e of save.edges) {
    edges.set(e.id, {
      id: e.id,
      v1: e.v1,
      v2: e.v2,
      points: e.points.map(p => ({ ...p })),
      // Placeholders — overwritten by recomputeRegions().
      leftRegion: 0,
      rightRegion: 0,
    });
  }

  const state: GameState = {
    vertices,
    edges,
    regions: new Map(),
    subpositions: [],
    nextVertexId: save.nextVertexId,
    nextEdgeId: save.nextEdgeId,
    nextRegionId: 0,
    moveCount: save.moveCount,
    // Placeholder — recomputed by the caller after recomputeRegions() settles
    // degrees, via recomputeSpotLabels replay or (cheaply) initialSpotLabels.
    spotLabels: new Map(),
  };

  const pendingMove = save.pendingMove
    ? parseToken(save.pendingMove.token, save.moveSequence.length + 1)
    : null;

  return {
    state,
    camera: [...save.camera] as RotationMatrix,
    currentSpotCount: save.currentSpotCount,
    moveSequence: [...save.moveSequence],
    pendingMove,
  };
}
