/**
 * Serialize/deserialize a GameState to a portable save file.
 *
 * Only the geometric layer (vertices, edges) and ID counters are saved per board.
 * regions/subpositions, vertex degree/type/visual, isPseudo vertices, and edge
 * leftRegion/rightRegion are all rebuilt by recomputeRegions() from vertices+edges
 * alone (see model/moves.ts), so none of that is stored here. Voronoi-cell data is
 * likewise never saved -- it's cheap to recompute on demand from a saved board via
 * buildSubregionHighlight/buildVoronoiGraph.
 *
 * v2 adds a full per-move history: the board immediately before each committed move,
 * plus the exact raw stroke used to make it (captured before smoothing physics ever
 * touches the resulting edge points). This lets a loaded game rewind all the way back
 * to its start via the normal undo stack, and gives a future Recreate rework the exact
 * original line for each move instead of having to re-synthesize a candidate stroke.
 */

import type { GameState, VertexId, EdgeId } from './types';
import { VertexType, VertexVisualState } from './types';
import type { SpherePoint, RotationMatrix } from '../math/sphere';
import type { ParsedMove } from './moveCodeParse';
import { parseToken } from './moveCodeParse';

const SCHEMA_VERSION = 2;

interface SavedVertex {
  id: VertexId;
  pos: SpherePoint;
  isMidpoint?: boolean;
}

interface SavedEdge {
  id: EdgeId;
  v1: VertexId;
  v2: VertexId;
  points: SpherePoint[];
}

interface SavedBoard {
  nextVertexId: VertexId;
  nextEdgeId: EdgeId;
  moveCount: number;
  vertices: SavedVertex[];
  edges: SavedEdge[];
}

/** One committed move: the board immediately before it, the endpoints, and the exact
 *  stroke used to make it. */
interface SavedStep {
  before: SavedBoard;
  v1: VertexId;
  v2: VertexId;
  rawStroke: SpherePoint[];
}

export interface SaveFileV2 {
  schemaVersion: 2;
  currentSpotCount: number;
  camera: RotationMatrix;
  moveSequence: string[];
  pendingMove: { token: string } | null;
  steps: SavedStep[];
  final: SavedBoard;
}

/** Shape a caller's undo-history array needs for serializeGameState -- matches main.ts's
 *  HistoryEntry closely enough to build from, without saveState.ts depending on main.ts. */
export interface HistoryStepInput {
  state: GameState;
  committed: { v1: VertexId; v2: VertexId; rawStroke: SpherePoint[] } | null;
}

function serializeBoard(state: GameState): SavedBoard {
  const vertices: SavedVertex[] = [];
  for (const v of state.vertices.values()) {
    if (v.isPseudo) continue; // regenerated by recomputeRegions; not real board state
    vertices.push({ id: v.id, pos: { ...v.pos }, isMidpoint: v.isMidpoint });
  }
  const edges: SavedEdge[] = [];
  for (const e of state.edges.values()) {
    edges.push({ id: e.id, v1: e.v1, v2: e.v2, points: e.points.map(p => ({ ...p })) });
  }
  return {
    nextVertexId: state.nextVertexId,
    nextEdgeId: state.nextEdgeId,
    moveCount: state.moveCount,
    vertices,
    edges,
  };
}

function deserializeBoard(board: SavedBoard): GameState {
  const vertices: GameState['vertices'] = new Map();
  for (const v of board.vertices) {
    vertices.set(v.id, {
      id: v.id,
      pos: { ...v.pos },
      // Placeholders -- overwritten by recomputeRegions()'s degree/classification pass.
      type: VertexType.Spot,
      degree: 0,
      visual: VertexVisualState.Active,
      isMidpoint: v.isMidpoint,
    });
  }

  const edges: GameState['edges'] = new Map();
  for (const e of board.edges) {
    edges.set(e.id, {
      id: e.id,
      v1: e.v1,
      v2: e.v2,
      points: e.points.map(p => ({ ...p })),
      // Placeholders -- overwritten by recomputeRegions().
      leftRegion: 0,
      rightRegion: 0,
    });
  }

  return {
    vertices,
    edges,
    regions: new Map(),
    subpositions: [],
    nextVertexId: board.nextVertexId,
    nextEdgeId: board.nextEdgeId,
    nextRegionId: 0,
    moveCount: board.moveCount,
    // Placeholder -- recomputed by the caller after recomputeRegions() settles degrees.
    spotLabels: new Map(),
  };
}

export function serializeGameState(
  state: GameState,
  camera: RotationMatrix,
  currentSpotCount: number,
  moveSequence: readonly string[],
  pendingMoveToken: string | null,
  history: readonly HistoryStepInput[],
): SaveFileV2 {
  const steps: SavedStep[] = [];
  for (const h of history) {
    if (!h.committed) continue; // an in-flight (uncommitted) snapshot should never reach save
    steps.push({
      before: serializeBoard(h.state),
      v1: h.committed.v1,
      v2: h.committed.v2,
      rawStroke: h.committed.rawStroke.map(p => ({ ...p })),
    });
  }
  return {
    schemaVersion: SCHEMA_VERSION,
    currentSpotCount,
    camera: [...camera] as RotationMatrix,
    moveSequence: [...moveSequence],
    pendingMove: pendingMoveToken !== null ? { token: pendingMoveToken } : null,
    steps,
    final: serializeBoard(state),
  };
}

export interface DeserializedSave {
  state: GameState;
  camera: RotationMatrix;
  currentSpotCount: number;
  moveSequence: string[];
  pendingMove: ParsedMove | null;
  /** One entry per committed move, in order -- the board just before it, the move, and its
   *  raw stroke. Caller (main.ts) turns each into a real HistoryEntry (after recomputeRegions +
   *  spot-label replay), so a loaded game can undo all the way back to its start. */
  history: HistoryStepInput[];
}

export function deserializeGameState(save: SaveFileV2): DeserializedSave {
  if (save.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`Unsupported save schemaVersion ${String(save.schemaVersion)} (expected ${SCHEMA_VERSION}).`);
  }

  const history: HistoryStepInput[] = save.steps.map(step => ({
    state: deserializeBoard(step.before),
    committed: { v1: step.v1, v2: step.v2, rawStroke: step.rawStroke.map(p => ({ ...p })) },
  }));

  const state = deserializeBoard(save.final);

  const pendingMove = save.pendingMove
    ? parseToken(save.pendingMove.token, save.moveSequence.length + 1)
    : null;

  return {
    state,
    camera: [...save.camera] as RotationMatrix,
    currentSpotCount: save.currentSpotCount,
    moveSequence: [...save.moveSequence],
    pendingMove,
    history,
  };
}
